// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFGpZojxHxqY0g_yZjUr5kudWNO8CA_M',
    appId: '1:656699802204:web:5414720b17e238eb2adc99',
    messagingSenderId: '656699802204',
    projectId: 'cnpp-58096',
    authDomain: 'cnpp-58096.firebaseapp.com',
    storageBucket: 'cnpp-58096.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxW7515k2vF-SgeM5MoTX5x4WdlZo2uo',
    appId: '1:656699802204:android:5546a6257fe133692adc99',
    messagingSenderId: '656699802204',
    projectId: 'cnpp-58096',
    storageBucket: 'cnpp-58096.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-G_Ic7_lXLgsmW0DXLLP7VEX3pSP4wAA',
    appId: '1:656699802204:ios:0c4e1b632bbe812d2adc99',
    messagingSenderId: '656699802204',
    projectId: 'cnpp-58096',
    storageBucket: 'cnpp-58096.firebasestorage.app',
    iosBundleId: 'com.example.cnpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-G_Ic7_lXLgsmW0DXLLP7VEX3pSP4wAA',
    appId: '1:656699802204:ios:0c4e1b632bbe812d2adc99',
    messagingSenderId: '656699802204',
    projectId: 'cnpp-58096',
    storageBucket: 'cnpp-58096.firebasestorage.app',
    iosBundleId: 'com.example.cnpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbFGpZojxHxqY0g_yZjUr5kudWNO8CA_M',
    appId: '1:656699802204:web:11ba532667a963dc2adc99',
    messagingSenderId: '656699802204',
    projectId: 'cnpp-58096',
    authDomain: 'cnpp-58096.firebaseapp.com',
    storageBucket: 'cnpp-58096.firebasestorage.app',
  );

}